apiVersion: v1
kind: Secret
metadata:
  name: {{ include "statuspage.fullname" . }}-secrets
  labels:
    {{- include "statuspage.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.azureTenantId }}
  azure-tenant-id: {{ .Values.secrets.azureTenantId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureClientId }}
  azure-client-id: {{ .Values.secrets.azureClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.azureClientSecret }}
  azure-client-secret: {{ .Values.secrets.azureClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.embedApiKey }}
  embed-api-key: {{ .Values.secrets.embedApiKey | b64enc | quote }}
  {{- end }}
